# build
FROM node:20 AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build -- --configuration production

# runtime
FROM nginx:alpine
COPY --from=build /app/dist/todo-frontend /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
